name: 💉Setup the project
description: Perform standard setup and install dependencies using deno.
inputs:
  deno_dir:
    description: 'The directory where deno dependencies are stored.'
    required: false
    default: 'my_cache_directory' # Set DENO_DIR to an absolute or relative path on the runner.
runs:
  using: composite
  steps:
    - name: 🛠️ Install deno
      uses: denoland/setup-deno@v2
      with:
        deno-version: v2.x

    #    - name: Cache Deno dependencies
    #      uses: actions/cache@v4
    #      with:
    #        path: ${{ inputs.deno_dir }}
    #        key: ${{ hashFiles('deno.lock') }}

    - name: 🧩 Install dependencies
      shell: bash
      run: deno install
