packages:
  - packages/*
catalog:
  "@biomejs/biome": 1.9.4
  "@changesets/cli": 2.27.12
  "@std/yaml": npm:@jsr/std__yaml@1.0.5
  "@tsconfig/node23": 23.0.0
  "@tsconfig/strictest": 2.0.5
  "@types/json-schema": 7.0.15
  "@types/node": 22.10.10
  "@vitest/coverage-v8": 3.0.4
  "@vitest/ui": 3.0.4
  effect: 3.12.7
  typescript: 5.7.3
  vitest: 3.0.4
