name: 🚀 Push Checks Workflow
on:
  push:
    branches-ignore:
      - main
  workflow_dispatch:

jobs:
  checks:
    name: 🫸 Push Checks
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Biome
        uses: biomejs/setup-biome@v2
        with:
          version: latest

      - name: 💅 Format packages/resume code (with Biome)
        continue-on-error: false
        run: |
          biome check \
          --vcs-enabled=true \
          --vcs-use-ignore-file=true \
          --vcs-root='.' \
          --formatter-enabled=true \
          --linter-enabled=false \
          --organize-imports-enabled=true \
          --write packages/resume

      - name: 💅 Format packages/schema-resume code (with Biome)
        continue-on-error: false
        run: |
          biome check \
          --vcs-enabled=true \
          --vcs-use-ignore-file=true \
          --vcs-root='.' \
          --formatter-enabled=true \
          --linter-enabled=false \
          --organize-imports-enabled=true \
          --write packages/schema-resume

      - name: 🚦 Git Auto Commit Lint fixes (with Biome)
        uses: stefanzweifel/git-auto-commit-action@v6.0.1
        with:
          commit_message: "chore: format code with Biome [skip ci]"
