name: 🚀 Push Checks Workflow
on:
  push:
    branches-ignore:
      - main
  workflow_dispatch:

jobs:
  checks:
    name: 🫸 Push Checks
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: 👣 Retrieve Git REF
        run: echo "GIT_REF=$(git rev-parse origin/main)" >> $GITHUB_ENV

      - name: 📦 Setup Deno and install deps
        uses: ./.github/actions/setup


      - name: 💅 Format code (with Biome)
        continue-on-error: true
        run: deno task --recursive format:write --since=${{ env.GIT_REF }}

      - name: 🚦 Git Auto Commit Lint fixes (with Biome)
        uses: stefanzweifel/git-auto-commit-action@v5.1.0
        with:
          commit_message: "chore: lint code with Biome [skip ci]"
