name: 🦋 Release

on:
  workflow_dispatch:


concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: 📥 Checkout code
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: 📦 Setup Deno and install deps
        uses: ./.github/actions/setup

      - name: 🦋 Create a Changeset Release Pull Request
        uses: changesets/action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          commit: "chore(🦋): update versions"
          title: "chore(🦋): Update Package Version"
